### ISSUE TITLE
Field to capture ERDDAP attribute <fileAccessBaseUrl>

### ISSUE THREAD

**Issue by whshannon** [BCODMO/Ocean-Data-Ontology#15]
We need a field to capture the ERDDAP attribute <fileAccessBaseUrl> 

This could be in OSPREY or perhaps part of Laminar and captured in the yaml? Not sure of the best place to fit this in the DM workflow... but this attribute would be associated with data files or docs linked from datasets.

As an example, see this dataset: https://www.bco-dmo.org/dataset/783880
It contains image file names in the associatedMedia column. Those images are located in /data302/Mariana_Back-arc_Vents/data_docs/783880
Base URL would be:  https://datadocs.bco-dmo.org/docs/Mariana_Back-arc_Vents/data_docs/783880/

See related issue in ERDDAP-BCODMO: https://github.com/BCODMO/ERDDAP-BCODMO/issues/65

**Comment by whshannon** [comment]
tagging @mbiddle-bcodmo so you can follow

**Comment by mbiddle-bcodmo** [comment]
There is also a tag for adding a suffix:
`<att name="fileAccessSuffix">someSuffix</a>`

Here is the ERDDAP documentation on both: https://erddap.bco-dmo.org/erddap/download/setupDatasetsXml.html#fileAccessBaseUrl

Here is a dataset on our production ERDDAP that uses the fileAccessBaseUrl: 
https://erddap.bco-dmo.org/erddap/tabledap/bcodmo_dataset_549122.htmlTable?light_image_filename%2Cchl_image_filename%2CSXRF_map_filename%2CSXRF_spectrum_filename%2Ctime

**Comment by ashepherd** [comment]
Fixed:
<img width="950" alt="Screen Shot 2020-02-16 at 8 20 10 PM" src="https://user-images.githubusercontent.com/2117576/74623516-cc20c580-50f9-11ea-9bab-6bd0b7988d15.png">

**Comment by mbiddle-bcodmo** [comment]
Thanks @ashepherd. I'll need to update my code to account for this. When populated, will the information be available at the mapserver api? Eg. https://www.bco-dmo.org/mapserver/dataset/549122/parameters

**Comment by ashepherd** [comment]
Yeah, I still gotta code that up 😀

**Comment by whshannon** [comment]
Thanks! Whenever this is ready to test, I've updated this dataset with a URL prefix: https://www.bco-dmo.org/dataset/783880

**Comment by ashepherd** [comment]
@mbiddle-bcodmo 
https://www.bco-dmo.org/api/dataset/783880/parameters

**Comment by mbiddle-bcodmo** [comment]
@whshannon have a look at https://erddap-test.bco-dmo.org/erddap/tabledap/bcodmo_dataset_783880.html

**Comment by whshannon** [comment]
The links to images all look good! What's the little question mark icon to the left of the link...is that supposed to show a tool tip? It doesn't do anything when I hover or click.

**Comment by mbiddle-bcodmo** [comment]
Great! The icon is suppose to be a hover over that shows a preview of the image, but we've been having trouble getting that functionality to work. I'll do some testing to see if we can get that working.

https://github.com/BCODMO/ERDDAP-BCODMO/issues/44

I noticed that you used the http:// address. Should we be using https:// ? @ashepherd thoughts?

**Comment by mbiddle-bcodmo** [comment]
https://github.com/BCODMO/ERDDAP-BCODMO/pull/77

**Comment by ashepherd** [comment]
Yeah https. It should be redirecting http to https but you can change it in the metadata to be safe
